resources:
  - url: http://127.0.0.1:5000/hass-3d-floorplan.js
    type: module
views:
  - cards:
      - type: custom:hass-3d-floorplan
        name: HASS 3D Floorplan Development
        entity: sun.sun
        test_gui: true
